import Link from "next/link";

const services = [
  ["VISAT", "Investigações e inspeções nos ambientes e processos de trabalho para identificar riscos e promover melhorias."],
  ["Medicina do Trabalho", "Diagnóstico, acompanhamento clínico, nexo causal e orientação em doenças relacionadas ao trabalho."],
  ["Fisioterapia", "Prevenção, avaliação e reabilitação de LER/DORT e outras lesões musculoesqueléticas ocupacionais."],
  ["Enfermagem", "Acolhimento, triagem, educação em saúde e assistência especializada ao trabalhador."],
  ["SINAN", "Registro, análise e monitoramento dos agravos e acidentes relacionados ao trabalho."],
  ["Políticas Sociais", "Orientação de direitos e articulação com a rede de proteção social e políticas públicas."],
];

export default function Home() {
  return <>
    <section className="hero"><div className="wrap hero-grid"><div className="hero-copy"><span className="eyebrow">Saúde do Trabalhador • SUS</span><h1>Proteção, cuidado e vigilância para quem trabalha.</h1><p>O CEREST Tianguá — Eduardo José da Silva é referência regional na prevenção, no diagnóstico e no acompanhamento de doenças e acidentes relacionados ao trabalho.</p><div className="actions"><Link className="button primary" href="/contato">Buscar orientação</Link><Link className="button ghost" href="/servicos">Conhecer as áreas de atuação</Link></div><p className="availability"><span /> Atendimento de segunda a sexta, 7h30–11h30 e 13h–17h</p></div><figure className="hero-photo"><img src="/fachada-cerest-tiangua.webp" alt="Fachada do CEREST Tianguá — Eduardo José da Silva" width="680" height="510" fetchPriority="high" decoding="async"/><figcaption>Fachada do CEREST Tianguá</figcaption></figure></div></section>
    <section className="quick wrap" aria-label="Acessos rápidos"><a href="https://wa.me/5588993112313"><b>Falar no WhatsApp</b><span>(88) 99311-2313</span></a><Link href="/educacao"><b>Material educativo</b><span>Prevenção e orientações</span></Link><Link href="/contato"><b>Notificar um acidente</b><span>Saiba como receber orientação</span></Link></section>
    <section className="section wrap split-intro"><div><span className="eyebrow">Nossa principal função</span><h2>Vigilância em Saúde do Trabalhador</h2></div><div><p>A VISAT investiga ambientes, processos e acidentes de trabalho. A partir da análise dos riscos, o CEREST orienta medidas de prevenção e articula ações com municípios e instituições parceiras.</p><Link className="text-link" href="/servicos">Entenda como atuamos →</Link></div></section>
    <section className="section soft"><div className="wrap"><span className="eyebrow">Atendimento integral</span><h2>Áreas de atuação</h2><div className="card-grid">{services.map(([title,text],i)=><article className="service-card" key={title}><span>0{i+1}</span><h3>{title}</h3><p>{text}</p></article>)}</div></div></section>
    <section className="section wrap story"><div className="story-mark">Eduardo<br/>José da<br/>Silva</div><div><span className="eyebrow">Um nome, um legado</span><h2>A luta dos trabalhadores faz parte da nossa história</h2><p>O CEREST homenageia o cavador de poços que, após adoecer por silicose, mobilizou seus companheiros e ajudou a fundar, em 1987, a Associação Regional dos Silicóticos da Ibiapaba. Seu trabalho abriu caminhos para assistência, direitos e condições mais dignas.</p><Link className="text-link" href="/sobre">Conheça essa história →</Link></div></section>
    <section className="section news wrap"><div className="section-head"><div><span className="eyebrow">Informação que protege</span><h2>Destaques do blog</h2></div><Link className="text-link" href="/blog">Ver todas as publicações →</Link></div><div className="news-grid"><Link href="/blog/silicose"><article><span>Prevenção</span><h3>Silicose: por que a poeira de sílica exige atenção permanente</h3><p>Entenda os riscos, os sinais e as medidas de prevenção.</p></article></Link><Link href="/blog/notificacao"><article><span>Orientação</span><h3>Acidente de trabalho: quando e como buscar orientação</h3><p>A notificação ajuda a revelar riscos e proteger outros trabalhadores.</p></article></Link><Link href="/blog/visat"><article><span>VISAT</span><h3>Como a vigilância transforma ambientes de trabalho</h3><p>Da investigação à recomendação de medidas preventivas.</p></article></Link></div></section>
    <section className="cta"><div className="wrap"><div><span className="eyebrow light">Atendimento gratuito pelo SUS</span><h2>Tem dúvida sobre saúde e trabalho?</h2><p>Nossa equipe está pronta para acolher, orientar e encaminhar.</p></div><a className="button white" href="https://wa.me/5588993112313">Conversar com a equipe</a></div></section>
  </>;
}
