import Link from "next/link";
import { ContactBand, PageHero } from "../../components";

export const metadata={title:"Doenças e agravos relacionados à saúde do trabalhador",description:"Conheça os principais agravos relacionados ao trabalho, os prazos de notificação e as medidas de prevenção."};

const agravos=[
  ["01","Acidente de trabalho grave","Acidente que resulta em lesão grave, amputação, internação, incapacidade permanente ou risco de morte.","Notificação imediata","acidente-grave.webp"],
  ["02","Exposição a material biológico","Exposição ocupacional a sangue ou outros materiais biológicos potencialmente contaminados.","Notificação semanal","material-biologico.webp"],
  ["03","Intoxicação exógena relacionada ao trabalho","Exposição a produtos químicos, agrotóxicos, metais pesados, gases, vapores ou solventes.","Notificação semanal","intoxicacao-exogena.webp"],
  ["04","Câncer relacionado ao trabalho","Neoplasia associada à exposição ocupacional a agentes químicos, físicos ou biológicos.","Notificação semanal","cancer-trabalho.webp"],
  ["05","Dermatoses ocupacionais","Doenças da pele causadas ou agravadas pelas atividades e condições de trabalho.","Notificação semanal","dermatoses.webp"],
  ["06","Distúrbio de voz relacionado ao trabalho","Alterações vocais, como rouquidão e fadiga vocal, decorrentes do uso profissional da voz.","Notificação semanal","disturbio-voz.webp"],
  ["07","LER/DORT","Lesões que afetam músculos, tendões, nervos, ligamentos e articulações, associadas a repetição, esforço e posturas inadequadas.","Notificação semanal","ler-dort.webp"],
  ["08","Perda auditiva relacionada ao trabalho — PAIR","Redução da audição decorrente da exposição ocupacional ao ruído.","Notificação semanal","pair.webp"],
  ["09","Pneumoconioses","Doenças pulmonares provocadas pela inalação de poeiras minerais durante o trabalho.","Notificação semanal","pneumoconioses.webp"],
  ["10","Transtornos mentais relacionados ao trabalho","Sofrimento psíquico associado ao trabalho, incluindo ansiedade, depressão, burnout e estresse ocupacional.","Notificação semanal","transtornos-mentais.webp"],
  ["11","Violência interpessoal","Agressões, ameaças, intimidações ou outras formas de violência entre pessoas no ambiente de trabalho.","Notificação semanal","violencia-interpessoal.webp"],
  ["12","Acidentes por animais peçonhentos","Acidentes causados por serpentes, escorpiões, aranhas, abelhas, vespas e outros animais peçonhentos.","Notificação semanal","animais-peconhentos.webp"],
  ["13","Outras intoxicações exógenas agudas","Intoxicação aguda por substâncias químicas, gases, vapores, fumos ou outras exposições no trabalho.","Notificação semanal","intoxicacao-exogena.webp"]
];
const prevencao=[["Ambiente de trabalho seguro e saudável","ambiente-seguro.webp"],["Uso de Equipamentos de Proteção Individual","epi.webp"],["Ergonomia e organização do trabalho","ergonomia.webp"],["Capacitação e informação aos trabalhadores","capacitacao.webp"],["Vigilância em Saúde do Trabalhador","visat.webp"],["Notificação e investigação dos agravos","notificacao-investigacao.webp"]];

export default function DoencasAgravos(){return <><PageHero label="Educação em Saúde" title="Doenças e agravos relacionados ao trabalho" intro="São doenças, lesões ou agravos à saúde adquiridos ou desencadeados pelas condições de trabalho e pela exposição a agentes e situações presentes no ambiente laboral."/><section className="section wrap folder-intro"><div><span className="eyebrow">Material educativo</span><h2>Identificar cedo também é proteger</h2><p>A identificação precoce, a notificação e a prevenção são essenciais para proteger a saúde do trabalhador e promover ambientes de trabalho mais seguros e saudáveis.</p><p>Em caso de suspeita, procure a Unidade de Saúde ou o CEREST do seu município.</p><a className="button primary" href="/educacao/folder-doencas-agravos.webp" target="_blank" rel="noreferrer">Abrir folder completo</a></div><img src="/educacao/folder-doencas-agravos.webp" alt="Folder sobre doenças e agravos relacionados à saúde do trabalhador" width="1445" height="1088" decoding="async"/></section><section className="section soft"><div className="wrap"><span className="eyebrow">Principais agravos</span><h2>O que deve receber atenção</h2><div className="agravo-grid">{agravos.map(([n,title,text,notice,img])=><article key={n}><img src={`/educacao/${img}`} alt={`Ilustração educativa: `} width="1400" height="788" loading="lazy" decoding="async"/><div><small>{n}</small><h3>{title}</h3><p>{text}</p><strong>{notice}</strong></div></article>)}</div></div></section><section className="section wrap"><span className="eyebrow">Agentes e fatores de risco</span><h2>Riscos presentes no trabalho</h2><div className="risk-row">{[["Físicos","Ruído, calor, frio, vibração, radiações e pressões anormais."],["Químicos","Poeiras, gases, vapores, fumos, agrotóxicos, solventes e metais."],["Biológicos","Vírus, bactérias, fungos, parasitas e materiais biológicos."],["Ergonômicos","Esforço físico, posturas inadequadas, repetição e ritmo excessivo."],["Psicossociais","Jornadas extensas, pressão, assédio, estresse e falta de controle."]].map(([t,d])=><div key={t}><b>{t}</b><span>{d}</span></div>)}</div></section><section className="section education-gallery"><div className="wrap"><span className="eyebrow light">Ações de prevenção</span><h2>Informação para ambientes mais seguros</h2><div className="prevention-grid">{prevencao.map(([title,img])=><article key={title}><img src={`/educacao/${img}`} alt={title} width="1536" height="1024" loading="lazy" decoding="async"/><h3>{title}</h3></article>)}</div></div></section><section className="section wrap notify-callout"><div><span className="eyebrow">Notificação</span><h2>Notificar é um ato de responsabilidade</h2><p>Notificar, investigar e acompanhar os agravos permite reconhecer suas causas, orientar medidas de prevenção e evitar novos casos.</p></div><Link className="button primary" href="/contato">Falar com o CEREST</Link></section><ContactBand/></>}
